# Site settings
title: Bits and Wires
header-img: img/home-bg.jpg
email: baiqizhang.xjtu@gmail.com
copyright_name: Baiqi Zhang
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://baiqizhang.github.io"
twitter_username: CopyCatPhoto
github_username:  baiqizhang
facebook_username:  baiqizhangcmu
email_username:  baiqizhang.xjtu@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
